// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorData.proto

package de.hszemi.sensorid_test;

public final class SensorData {
  private SensorData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SensorDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensorid_test.SensorDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string displayname = 1;</code>
     */
    boolean hasDisplayname();
    /**
     * <code>required string displayname = 1;</code>
     */
    java.lang.String getDisplayname();
    /**
     * <code>required string displayname = 1;</code>
     */
    com.google.protobuf.ByteString
        getDisplaynameBytes();

    /**
     * <code>required string sensorname = 2;</code>
     */
    boolean hasSensorname();
    /**
     * <code>required string sensorname = 2;</code>
     */
    java.lang.String getSensorname();
    /**
     * <code>required string sensorname = 2;</code>
     */
    com.google.protobuf.ByteString
        getSensornameBytes();

    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    java.util.List<de.hszemi.sensorid_test.SensorData.SensorReading> 
        getSensorreadingList();
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    de.hszemi.sensorid_test.SensorData.SensorReading getSensorreading(int index);
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    int getSensorreadingCount();
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    java.util.List<? extends de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder> 
        getSensorreadingOrBuilderList();
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder getSensorreadingOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code sensorid_test.SensorDataMessage}
   */
  public static final class SensorDataMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sensorid_test.SensorDataMessage)
      SensorDataMessageOrBuilder {
    // Use SensorDataMessage.newBuilder() to construct.
    private SensorDataMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SensorDataMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SensorDataMessage defaultInstance;
    public static SensorDataMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SensorDataMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SensorDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              displayname_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sensorname_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sensorreading_ = new java.util.ArrayList<de.hszemi.sensorid_test.SensorData.SensorReading>();
                mutable_bitField0_ |= 0x00000004;
              }
              sensorreading_.add(input.readMessage(de.hszemi.sensorid_test.SensorData.SensorReading.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sensorreading_ = java.util.Collections.unmodifiableList(sensorreading_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hszemi.sensorid_test.SensorData.SensorDataMessage.class, de.hszemi.sensorid_test.SensorData.SensorDataMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SensorDataMessage> PARSER =
        new com.google.protobuf.AbstractParser<SensorDataMessage>() {
      public SensorDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorDataMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SensorDataMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DISPLAYNAME_FIELD_NUMBER = 1;
    private java.lang.Object displayname_;
    /**
     * <code>required string displayname = 1;</code>
     */
    public boolean hasDisplayname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string displayname = 1;</code>
     */
    public java.lang.String getDisplayname() {
      java.lang.Object ref = displayname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string displayname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDisplaynameBytes() {
      java.lang.Object ref = displayname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSORNAME_FIELD_NUMBER = 2;
    private java.lang.Object sensorname_;
    /**
     * <code>required string sensorname = 2;</code>
     */
    public boolean hasSensorname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sensorname = 2;</code>
     */
    public java.lang.String getSensorname() {
      java.lang.Object ref = sensorname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sensorname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sensorname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSensornameBytes() {
      java.lang.Object ref = sensorname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSORREADING_FIELD_NUMBER = 3;
    private java.util.List<de.hszemi.sensorid_test.SensorData.SensorReading> sensorreading_;
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    public java.util.List<de.hszemi.sensorid_test.SensorData.SensorReading> getSensorreadingList() {
      return sensorreading_;
    }
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    public java.util.List<? extends de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder> 
        getSensorreadingOrBuilderList() {
      return sensorreading_;
    }
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    public int getSensorreadingCount() {
      return sensorreading_.size();
    }
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    public de.hszemi.sensorid_test.SensorData.SensorReading getSensorreading(int index) {
      return sensorreading_.get(index);
    }
    /**
     * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
     */
    public de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder getSensorreadingOrBuilder(
        int index) {
      return sensorreading_.get(index);
    }

    private void initFields() {
      displayname_ = "";
      sensorname_ = "";
      sensorreading_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDisplayname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSensorname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSensorreadingCount(); i++) {
        if (!getSensorreading(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDisplaynameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSensornameBytes());
      }
      for (int i = 0; i < sensorreading_.size(); i++) {
        output.writeMessage(3, sensorreading_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDisplaynameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSensornameBytes());
      }
      for (int i = 0; i < sensorreading_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, sensorreading_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.hszemi.sensorid_test.SensorData.SensorDataMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensorid_test.SensorDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensorid_test.SensorDataMessage)
        de.hszemi.sensorid_test.SensorData.SensorDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.hszemi.sensorid_test.SensorData.SensorDataMessage.class, de.hszemi.sensorid_test.SensorData.SensorDataMessage.Builder.class);
      }

      // Construct using de.hszemi.sensorid_test.SensorData.SensorDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSensorreadingFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        displayname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sensorname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (sensorreadingBuilder_ == null) {
          sensorreading_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          sensorreadingBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorDataMessage_descriptor;
      }

      public de.hszemi.sensorid_test.SensorData.SensorDataMessage getDefaultInstanceForType() {
        return de.hszemi.sensorid_test.SensorData.SensorDataMessage.getDefaultInstance();
      }

      public de.hszemi.sensorid_test.SensorData.SensorDataMessage build() {
        de.hszemi.sensorid_test.SensorData.SensorDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.hszemi.sensorid_test.SensorData.SensorDataMessage buildPartial() {
        de.hszemi.sensorid_test.SensorData.SensorDataMessage result = new de.hszemi.sensorid_test.SensorData.SensorDataMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.displayname_ = displayname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sensorname_ = sensorname_;
        if (sensorreadingBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            sensorreading_ = java.util.Collections.unmodifiableList(sensorreading_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.sensorreading_ = sensorreading_;
        } else {
          result.sensorreading_ = sensorreadingBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.hszemi.sensorid_test.SensorData.SensorDataMessage) {
          return mergeFrom((de.hszemi.sensorid_test.SensorData.SensorDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.hszemi.sensorid_test.SensorData.SensorDataMessage other) {
        if (other == de.hszemi.sensorid_test.SensorData.SensorDataMessage.getDefaultInstance()) return this;
        if (other.hasDisplayname()) {
          bitField0_ |= 0x00000001;
          displayname_ = other.displayname_;
          onChanged();
        }
        if (other.hasSensorname()) {
          bitField0_ |= 0x00000002;
          sensorname_ = other.sensorname_;
          onChanged();
        }
        if (sensorreadingBuilder_ == null) {
          if (!other.sensorreading_.isEmpty()) {
            if (sensorreading_.isEmpty()) {
              sensorreading_ = other.sensorreading_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSensorreadingIsMutable();
              sensorreading_.addAll(other.sensorreading_);
            }
            onChanged();
          }
        } else {
          if (!other.sensorreading_.isEmpty()) {
            if (sensorreadingBuilder_.isEmpty()) {
              sensorreadingBuilder_.dispose();
              sensorreadingBuilder_ = null;
              sensorreading_ = other.sensorreading_;
              bitField0_ = (bitField0_ & ~0x00000004);
              sensorreadingBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSensorreadingFieldBuilder() : null;
            } else {
              sensorreadingBuilder_.addAllMessages(other.sensorreading_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDisplayname()) {
          
          return false;
        }
        if (!hasSensorname()) {
          
          return false;
        }
        for (int i = 0; i < getSensorreadingCount(); i++) {
          if (!getSensorreading(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.hszemi.sensorid_test.SensorData.SensorDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.hszemi.sensorid_test.SensorData.SensorDataMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object displayname_ = "";
      /**
       * <code>required string displayname = 1;</code>
       */
      public boolean hasDisplayname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string displayname = 1;</code>
       */
      public java.lang.String getDisplayname() {
        java.lang.Object ref = displayname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            displayname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string displayname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDisplaynameBytes() {
        java.lang.Object ref = displayname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string displayname = 1;</code>
       */
      public Builder setDisplayname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        displayname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string displayname = 1;</code>
       */
      public Builder clearDisplayname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        displayname_ = getDefaultInstance().getDisplayname();
        onChanged();
        return this;
      }
      /**
       * <code>required string displayname = 1;</code>
       */
      public Builder setDisplaynameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        displayname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sensorname_ = "";
      /**
       * <code>required string sensorname = 2;</code>
       */
      public boolean hasSensorname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public java.lang.String getSensorname() {
        java.lang.Object ref = sensorname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sensorname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSensornameBytes() {
        java.lang.Object ref = sensorname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensorname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public Builder setSensorname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sensorname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public Builder clearSensorname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sensorname_ = getDefaultInstance().getSensorname();
        onChanged();
        return this;
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public Builder setSensornameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sensorname_ = value;
        onChanged();
        return this;
      }

      private java.util.List<de.hszemi.sensorid_test.SensorData.SensorReading> sensorreading_ =
        java.util.Collections.emptyList();
      private void ensureSensorreadingIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sensorreading_ = new java.util.ArrayList<de.hszemi.sensorid_test.SensorData.SensorReading>(sensorreading_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.hszemi.sensorid_test.SensorData.SensorReading, de.hszemi.sensorid_test.SensorData.SensorReading.Builder, de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder> sensorreadingBuilder_;

      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public java.util.List<de.hszemi.sensorid_test.SensorData.SensorReading> getSensorreadingList() {
        if (sensorreadingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sensorreading_);
        } else {
          return sensorreadingBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public int getSensorreadingCount() {
        if (sensorreadingBuilder_ == null) {
          return sensorreading_.size();
        } else {
          return sensorreadingBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public de.hszemi.sensorid_test.SensorData.SensorReading getSensorreading(int index) {
        if (sensorreadingBuilder_ == null) {
          return sensorreading_.get(index);
        } else {
          return sensorreadingBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder setSensorreading(
          int index, de.hszemi.sensorid_test.SensorData.SensorReading value) {
        if (sensorreadingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorreadingIsMutable();
          sensorreading_.set(index, value);
          onChanged();
        } else {
          sensorreadingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder setSensorreading(
          int index, de.hszemi.sensorid_test.SensorData.SensorReading.Builder builderForValue) {
        if (sensorreadingBuilder_ == null) {
          ensureSensorreadingIsMutable();
          sensorreading_.set(index, builderForValue.build());
          onChanged();
        } else {
          sensorreadingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder addSensorreading(de.hszemi.sensorid_test.SensorData.SensorReading value) {
        if (sensorreadingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorreadingIsMutable();
          sensorreading_.add(value);
          onChanged();
        } else {
          sensorreadingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder addSensorreading(
          int index, de.hszemi.sensorid_test.SensorData.SensorReading value) {
        if (sensorreadingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorreadingIsMutable();
          sensorreading_.add(index, value);
          onChanged();
        } else {
          sensorreadingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder addSensorreading(
          de.hszemi.sensorid_test.SensorData.SensorReading.Builder builderForValue) {
        if (sensorreadingBuilder_ == null) {
          ensureSensorreadingIsMutable();
          sensorreading_.add(builderForValue.build());
          onChanged();
        } else {
          sensorreadingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder addSensorreading(
          int index, de.hszemi.sensorid_test.SensorData.SensorReading.Builder builderForValue) {
        if (sensorreadingBuilder_ == null) {
          ensureSensorreadingIsMutable();
          sensorreading_.add(index, builderForValue.build());
          onChanged();
        } else {
          sensorreadingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder addAllSensorreading(
          java.lang.Iterable<? extends de.hszemi.sensorid_test.SensorData.SensorReading> values) {
        if (sensorreadingBuilder_ == null) {
          ensureSensorreadingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sensorreading_);
          onChanged();
        } else {
          sensorreadingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder clearSensorreading() {
        if (sensorreadingBuilder_ == null) {
          sensorreading_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          sensorreadingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public Builder removeSensorreading(int index) {
        if (sensorreadingBuilder_ == null) {
          ensureSensorreadingIsMutable();
          sensorreading_.remove(index);
          onChanged();
        } else {
          sensorreadingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public de.hszemi.sensorid_test.SensorData.SensorReading.Builder getSensorreadingBuilder(
          int index) {
        return getSensorreadingFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder getSensorreadingOrBuilder(
          int index) {
        if (sensorreadingBuilder_ == null) {
          return sensorreading_.get(index);  } else {
          return sensorreadingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public java.util.List<? extends de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder> 
           getSensorreadingOrBuilderList() {
        if (sensorreadingBuilder_ != null) {
          return sensorreadingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sensorreading_);
        }
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public de.hszemi.sensorid_test.SensorData.SensorReading.Builder addSensorreadingBuilder() {
        return getSensorreadingFieldBuilder().addBuilder(
            de.hszemi.sensorid_test.SensorData.SensorReading.getDefaultInstance());
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public de.hszemi.sensorid_test.SensorData.SensorReading.Builder addSensorreadingBuilder(
          int index) {
        return getSensorreadingFieldBuilder().addBuilder(
            index, de.hszemi.sensorid_test.SensorData.SensorReading.getDefaultInstance());
      }
      /**
       * <code>repeated .sensorid_test.SensorReading sensorreading = 3;</code>
       */
      public java.util.List<de.hszemi.sensorid_test.SensorData.SensorReading.Builder> 
           getSensorreadingBuilderList() {
        return getSensorreadingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.hszemi.sensorid_test.SensorData.SensorReading, de.hszemi.sensorid_test.SensorData.SensorReading.Builder, de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder> 
          getSensorreadingFieldBuilder() {
        if (sensorreadingBuilder_ == null) {
          sensorreadingBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.hszemi.sensorid_test.SensorData.SensorReading, de.hszemi.sensorid_test.SensorData.SensorReading.Builder, de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder>(
                  sensorreading_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          sensorreading_ = null;
        }
        return sensorreadingBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:sensorid_test.SensorDataMessage)
    }

    static {
      defaultInstance = new SensorDataMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sensorid_test.SensorDataMessage)
  }

  public interface SensorReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensorid_test.SensorReading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>required float x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 2;</code>
     */
    float getX();

    /**
     * <code>optional float y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>optional float y = 3;</code>
     */
    float getY();

    /**
     * <code>optional float z = 4;</code>
     */
    boolean hasZ();
    /**
     * <code>optional float z = 4;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code sensorid_test.SensorReading}
   */
  public static final class SensorReading extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sensorid_test.SensorReading)
      SensorReadingOrBuilder {
    // Use SensorReading.newBuilder() to construct.
    private SensorReading(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SensorReading(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SensorReading defaultInstance;
    public static SensorReading getDefaultInstance() {
      return defaultInstance;
    }

    public SensorReading getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SensorReading(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorReading_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorReading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hszemi.sensorid_test.SensorData.SensorReading.class, de.hszemi.sensorid_test.SensorData.SensorReading.Builder.class);
    }

    public static com.google.protobuf.Parser<SensorReading> PARSER =
        new com.google.protobuf.AbstractParser<SensorReading>() {
      public SensorReading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorReading(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SensorReading> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>required float x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float x = 2;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>optional float y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float y = 3;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 4;
    private float z_;
    /**
     * <code>optional float z = 4;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float z = 4;</code>
     */
    public float getZ() {
      return z_;
    }

    private void initFields() {
      timestamp_ = 0L;
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid_test.SensorData.SensorReading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.hszemi.sensorid_test.SensorData.SensorReading prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensorid_test.SensorReading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensorid_test.SensorReading)
        de.hszemi.sensorid_test.SensorData.SensorReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorReading_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorReading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.hszemi.sensorid_test.SensorData.SensorReading.class, de.hszemi.sensorid_test.SensorData.SensorReading.Builder.class);
      }

      // Construct using de.hszemi.sensorid_test.SensorData.SensorReading.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.hszemi.sensorid_test.SensorData.internal_static_sensorid_test_SensorReading_descriptor;
      }

      public de.hszemi.sensorid_test.SensorData.SensorReading getDefaultInstanceForType() {
        return de.hszemi.sensorid_test.SensorData.SensorReading.getDefaultInstance();
      }

      public de.hszemi.sensorid_test.SensorData.SensorReading build() {
        de.hszemi.sensorid_test.SensorData.SensorReading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.hszemi.sensorid_test.SensorData.SensorReading buildPartial() {
        de.hszemi.sensorid_test.SensorData.SensorReading result = new de.hszemi.sensorid_test.SensorData.SensorReading(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.hszemi.sensorid_test.SensorData.SensorReading) {
          return mergeFrom((de.hszemi.sensorid_test.SensorData.SensorReading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.hszemi.sensorid_test.SensorData.SensorReading other) {
        if (other == de.hszemi.sensorid_test.SensorData.SensorReading.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.hszemi.sensorid_test.SensorData.SensorReading parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.hszemi.sensorid_test.SensorData.SensorReading) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float x_ ;
      /**
       * <code>required float x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float x = 2;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>optional float y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float y = 3;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>optional float y = 3;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>optional float z = 4;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float z = 4;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>optional float z = 4;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000008;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float z = 4;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sensorid_test.SensorReading)
    }

    static {
      defaultInstance = new SensorReading(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sensorid_test.SensorReading)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensorid_test_SensorDataMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensorid_test_SensorDataMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensorid_test_SensorReading_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensorid_test_SensorReading_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SensorData.proto\022\rsensorid_test\"q\n\021Sen" +
      "sorDataMessage\022\023\n\013displayname\030\001 \002(\t\022\022\n\ns" +
      "ensorname\030\002 \002(\t\0223\n\rsensorreading\030\003 \003(\0132\034" +
      ".sensorid_test.SensorReading\"C\n\rSensorRe" +
      "ading\022\021\n\ttimestamp\030\001 \002(\003\022\t\n\001x\030\002 \002(\002\022\t\n\001y" +
      "\030\003 \001(\002\022\t\n\001z\030\004 \001(\002B\031\n\027de.hszemi.sensorid_" +
      "test"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sensorid_test_SensorDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensorid_test_SensorDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensorid_test_SensorDataMessage_descriptor,
        new java.lang.String[] { "Displayname", "Sensorname", "Sensorreading", });
    internal_static_sensorid_test_SensorReading_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sensorid_test_SensorReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensorid_test_SensorReading_descriptor,
        new java.lang.String[] { "Timestamp", "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
